#!/usr/bin/env node

/**
 * Environment Variable Loader for Angular
 * Loads environment variables and makes them available to the Angular app
 * Supports .env files for development and direct env vars for production
 */

const fs = require('fs');
const path = require('path');

// Load environment variables from .env file if it exists
function loadDotEnv() {
  const envPath = path.join(__dirname, '..', '.env');
  
  if (fs.existsSync(envPath)) {
    console.log('🔧 Loading environment variables from .env file...');
    const envContent = fs.readFileSync(envPath, 'utf8');
    
    envContent.split('\n').forEach(line => {
      const match = line.match(/^([^#=]+)=(.*)$/);
      if (match) {
        const [, key, value] = match;
        process.env[key.trim()] = value.trim().replace(/^["']|["']$/g, '');
      }
    });
  } else {
    console.log('ℹ️  No .env file found, using system environment variables');
  }
}

// Create a JavaScript file that exposes env vars to Angular
function createEnvFile() {
  const envVars = {
    NG_APP_FIREBASE_API_KEY: process.env.NG_APP_FIREBASE_API_KEY || process.env.FIREBASE_API_KEY,
    NG_APP_FIREBASE_AUTH_DOMAIN: process.env.NG_APP_FIREBASE_AUTH_DOMAIN || process.env.FIREBASE_AUTH_DOMAIN,
    NG_APP_FIREBASE_PROJECT_ID: process.env.NG_APP_FIREBASE_PROJECT_ID || process.env.FIREBASE_PROJECT_ID,
    NG_APP_FIREBASE_STORAGE_BUCKET: process.env.NG_APP_FIREBASE_STORAGE_BUCKET || process.env.FIREBASE_STORAGE_BUCKET,
    NG_APP_FIREBASE_MESSAGING_SENDER_ID: process.env.NG_APP_FIREBASE_MESSAGING_SENDER_ID || process.env.FIREBASE_MESSAGING_SENDER_ID,
    NG_APP_FIREBASE_APP_ID: process.env.NG_APP_FIREBASE_APP_ID || process.env.FIREBASE_APP_ID,
    NG_APP_ADMIN_PASSWORD: process.env.NG_APP_ADMIN_PASSWORD || process.env.ADMIN_PASSWORD,
  };

  const envScript = `
// Auto-generated environment variables
// DO NOT EDIT - This file is generated by scripts/load-env.js

${Object.entries(envVars).map(([key, value]) => 
  `globalThis.${key} = ${JSON.stringify(value || '')};`
).join('\n')}

console.log('🔥 Environment variables loaded for Angular app');
`;

  const outputPath = path.join(__dirname, '..', 'src', 'assets', 'env.js');
  const assetsDir = path.dirname(outputPath);
  
  // Ensure assets directory exists
  if (!fs.existsSync(assetsDir)) {
    fs.mkdirSync(assetsDir, { recursive: true });
  }
  
  fs.writeFileSync(outputPath, envScript);
  console.log('✅ Environment variables written to assets/env.js');
  
  // Log which variables were set (without showing values for security)
  const setVars = Object.entries(envVars).filter(([, value]) => value).map(([key]) => key);
  const missingVars = Object.entries(envVars).filter(([, value]) => !value).map(([key]) => key);
  
  if (setVars.length > 0) {
    console.log('✅ Environment variables set:', setVars.join(', '));
  }
  
  if (missingVars.length > 0) {
    console.log('⚠️  Missing environment variables:', missingVars.join(', '));
    console.log('💡 Add these to your .env file or set them as system environment variables');
  }
}

// Main execution
try {
  loadDotEnv();
  createEnvFile();
} catch (error) {
  console.error('❌ Error loading environment variables:', error.message);
  process.exit(1);
}